steps:
  - name: quay.io/gravitational/docs:main
    id: docs-test
    entrypoint: /bin/bash
    dir: /src
    args:
      - -c
      - ln -s /workspace /src/content && yarn markdown-lint
    timeout: 10m
